import Image from "next/image";
import type { CSSProperties } from "react";

type Chapter = { n:string; title:string; lead:string; body:string; tag:string; href:string; link:string; note?:string; image?:string; imageAlt?:string };
type Researcher = { name:string; initials:string; field:string; bio:string; contribution:string; href:string; source:string; group:string; evidence:string; featured?:boolean };
type ResearcherPhoto = { src:string; credit:string; href:string; position?:string };

const chapters: Chapter[] = [
  {n:"01",title:"Qué es la vibroacústica aplicada al cuerpo",lead:"Sonido que se escucha y vibración que se siente.",body:"La vibroacústica aplica sonido audible —con especial presencia de bajas frecuencias— transmitido por el aire, por una superficie o por contacto. El Gong despliega un espectro complejo y dinámico cuya experiencia se configura mediante la distancia, la intensidad, el tiempo, el entorno y la sensibilidad de cada persona.",tag:"Punto de partida",href:"https://pmc.ncbi.nlm.nih.gov/articles/PMC8157227/",link:"Revisión de mecanismos",image:"/images/capitulo-01-vibroacustica.webp",imageAlt:"El Gong produce ondas que se escuchan y se sienten en el cuerpo"},
  {n:"02",title:"El sonido como onda mecánica",lead:"Una forma de energía que viaja a través de la materia.",body:"El sonido es una variación de presión que desplaza energía a través del aire, los líquidos y los tejidos. La ciencia caracteriza cada estímulo mediante frecuencia, amplitud, forma de onda, duración y vía de entrega. El conjunto de estas variables permite estudiar de manera precisa su interacción con el organismo.",tag:"Física",href:"https://www.ncbi.nlm.nih.gov/books/NBK538295/",link:"Fundamentos del sonido",image:"/images/capitulo-02-onda-mecanica.webp",imageAlt:"Una onda sonora del Gong propagándose por aire, agua y tejido"},
  {n:"03",title:"El cuerpo como órgano de percepción vibratoria",lead:"Percibir integra escuchar, sentir y dar significado.",body:"La experiencia vibroacústica combina audición y somatosensación. El sistema nervioso integra la información del oído con presión, tacto, postura, respiración, memoria, expectativa y contexto. Esa integración multisensorial convierte cada experiencia en una lectura corporal singular.",tag:"Integración sensorial",href:"https://pmc.ncbi.nlm.nih.gov/articles/PMC8157227/",link:"Vías auditiva y somática",image:"/images/capitulo-03-percepcion-vibratoria.webp",imageAlt:"El cuerpo integra sonido, tacto y significado como experiencia vibratoria"},
  {n:"04",title:"Mecanorreceptores, piel, fascia y dermatomas",lead:"La piel transforma vibración en información nerviosa.",body:"Los mecanorreceptores detectan presión, estiramiento y vibración en distintos rangos. La fascia distribuye cargas entre tejidos y los dermatomas organizan territorios cutáneos vinculados a raíces espinales. Juntos aportan un mapa neuroanatómico para comprender cómo el cuerpo recibe y localiza información mecánica.",tag:"Neuroanatomía",href:"https://www.ncbi.nlm.nih.gov/books/NBK541068/",link:"Mecanorreceptores cutáneos",image:"/images/capitulo-04-mecanorreceptores.webp",imageAlt:"La vibración activa receptores de la piel y se transforma en señales nerviosas"},
  {n:"05",title:"Interocepción, propiocepción y sistema nervioso autónomo",lead:"Sentir el cuerpo amplía la capacidad de regularlo.",body:"La interocepción permite sentir, interpretar, integrar y regular señales internas. La propiocepción informa posición y movimiento. Respiración, atención y sensación de seguridad enriquecen esta conversación cerebro–cuerpo y convierten la vibroacústica en una práctica de aprendizaje somático situada en el presente.",tag:"Regulación",href:"https://www.nccih.nih.gov/about/nccih-strategic-plan-2021-2025/top-scientific-priorities/interoception-research",link:"Ciencia de la interocepción · NIH",image:"/images/capitulo-05-interocepcion.webp",imageAlt:"Una persona percibe señales internas, postura y regulación del sistema nervioso"},
  {n:"06",title:"Mecanotransducción y respuesta biológica",lead:"Una fuerza mecánica puede convertirse en señal celular.",body:"Las células responden a tensión, compresión y cizallamiento mediante canales iónicos, adhesiones y citoesqueleto. La mecanotransducción conecta fuerzas físicas con señalización y expresión génica. Este mecanismo brinda una base biológica para diseñar investigaciones que relacionen estímulo, dosis, contexto y respuesta.",tag:"Biología celular",href:"https://pmc.ncbi.nlm.nih.gov/articles/PMC2614693/",link:"Tensegridad y mecanotransducción",image:"/images/capitulo-06-mecanotransduccion.webp",imageAlt:"Una fuerza mecánica alcanza una célula y activa su red de señalización"},
  {n:"07",title:"Fascia y biotensegridad",lead:"Continuidad mecánica para comprender la organización corporal.",body:"La fascia forma una red conectiva continua que transmite tensión y facilita el deslizamiento entre estructuras. La biotensegridad estudia el cuerpo como una organización de tensión y compresión distribuida. Su valor científico reside en orientar preguntas medibles sobre carga, movimiento y adaptación tisular.",tag:"Modelo mecánico",href:"https://pmc.ncbi.nlm.nih.gov/articles/PMC6682397/",link:"Marco científico del modelo",image:"/images/capitulo-07-biotensegridad.webp",imageAlt:"La red fascial distribuye tensión y compresión durante el movimiento"},
  {n:"08",title:"Sonocitología y vibración celular",lead:"La tecnología vuelve audibles movimientos celulares nanométricos.",body:"La sonocitología registra movimientos celulares mediante microscopía de fuerza atómica y los transforma en audio para su análisis. Esta sonificación abre una ventana experimental sobre la dinámica celular y muestra cómo una señal mecánica puede convertirse en información perceptible y estudiable.",tag:"Frontera experimental",href:"https://dash.harvard.edu/bitstreams/7312037c-fba0-6bd4-e053-0100007fdf3b/download",link:"Contexto científico de la sonocitología",image:"/images/capitulo-08-sonocitologia.webp",imageAlt:"Instrumentación científica convierte el nanomovimiento celular en una señal audible"},
  {n:"09",title:"Historia científica de la vibroacústica",lead:"De observar patrones a transmitir bajas frecuencias al cuerpo.",body:"Chladni hizo visibles los modos de vibración; Helmholtz estudió la percepción tonal y von Békésy la mecánica coclear. A finales del siglo XX, Olav Skille y Tony Wigram sistematizaron la Vibroacoustic Therapy con sonido de baja frecuencia transmitido por transductores.",tag:"Línea histórica",href:"https://journals.sagepub.com/doi/10.1177/135945758900300202",link:"Artículo histórico de 1989",image:"/images/capitulo-09-historia.webp",imageAlt:"Recorrido histórico desde los patrones de Chladni hasta la terapia vibroacústica"},
  {n:"10",title:"Prácticas mente–cuerpo y NCCIH de EE. UU.",lead:"Intervenciones multicomponente para la salud de la persona completa.",body:"El NCCIH estudia prácticas que actúan sobre las interacciones cerebro–cuerpo y reconoce la integración de componentes físicos y psicológicos. Respiración, atención, contexto y sonido conforman variables diferenciables dentro de una experiencia que puede articularse con el cuidado profesional de la salud.",tag:"Marco institucional",href:"https://www.nccih.nih.gov/health/mind-and-body-practices",link:"Marco oficial NCCIH",image:"/images/capitulo-10-mente-cuerpo.webp",imageAlt:"Sesión de Gong con una persona recostada sobre una cama vibroacústica elevada con transductores integrados"},
  {n:"11",title:"Medición trazable y desarrollo del WIBindex",lead:"El protocolo pre/post se convierte en una lectura comparable del bienestar.",body:"Bienestar Vibracional desarrolló e implementó el WIBindex como sistema propio de organización y lectura de datos. La cámara GDV Bio‑Well aplica impulsos eléctricos breves y registra el resplandor generado por una emisión optoelectrónica estimulada en la superficie de la piel; el software procesa esas imágenes para obtener parámetros comparables. La versión 1.0 ordena Estrés y Energía; la 1.1 integra Estrés fisiológico, Energía funcional y Balance neurovegetativo; y la 2.0 incorpora HRV y coherencia cardio‑cerebral con HeartMath.",tag:"Instrumentación",href:"#wibindex",link:"Ver evolución del WIBindex",note:"El WIBindex integra el registro GDV como indicador funcional, educativo y comparativo dentro del contexto completo de cada medición.",image:"/images/capitulo-11-medicion-trazable.webp",imageAlt:"Medición conjunta con Bio-Well GDV y emWave Pro para visualizar registros digitales, HRV y coherencia"},
  {n:"12",title:"Evidencia de campo de Bienestar Vibracional",lead:"Cada medición pre/post con WIBindex transforma una experiencia en aprendizaje investigable.",body:"La tesis de fin de formación documenta cambios posteriores a una sesión de Gong mediante imágenes electrofotónicas registradas con cámara GDV Bio‑Well. El procesamiento informático permite comparar los parámetros obtenidos antes y después. Sobre esta experiencia de campo se desarrolló una metodología que hoy se implementa mediante WIBindex 1.0, 1.1 y 2.0 para ordenar tendencias, perfeccionar protocolos y reunir series comparables.",tag:"Caso de campo",href:"https://iiterapiadesonido.es/aumento-de-la-energia-disponible-en-el-sistema-nervioso-central-y-reduccion-del-estres-post-sesion-de-gong-medido-mediante-la-tecnologia-camara-gdv/",link:"Leer la tesis completa"},
  {n:"13",title:"Framework BV: Wellness Intelligence Data‑Driven",lead:"Experiencia corporal + contexto + WIBindex.",body:"El Framework BV integra vibroacústica, Inteligencia Somática y medición pre/post mediante WIBindex. La práctica educa la capacidad de percibir, interpretar, integrar y regular señales corporales; el índice organiza tendencias y el diseño de datos preserva el contexto. El resultado es un aprendizaje personalizado, progresivo y trazable.",tag:"Síntesis BV",href:"#principios",link:"Ver los principios del framework"},
];

const researchers: Researcher[] = [
  {name:"Lee Bartel",initials:"LB",field:"Vibroacústica y neurociencia musical",bio:"Profesor emérito de la Universidad de Toronto y fundador del Music and Health Research Collaboratory. Su carrera conecta educación musical, salud y neurociencia.",contribution:"Investiga el sonido pulsado y la estimulación vibroacústica, con especial atención a dolor, neurodegeneración y estimulación rítmica en torno a 40 Hz.",href:"https://music.utoronto.ca/person/lee-bartel",source:"Universidad de Toronto",group:"Vibroacústica y sonido",evidence:"Investigación clínica",featured:true},
  {name:"Olav Skille",initials:"OS",field:"Vibroacoustic Therapy",bio:"Educador y terapeuta noruego asociado al desarrollo temprano de la Vibroacoustic Therapy durante la segunda mitad del siglo XX.",contribution:"Sistematizó la transmisión de sonido de baja frecuencia al cuerpo mediante camas y sillas con transductores, abriendo una línea clínica específica.",href:"https://journals.sagepub.com/doi/10.1177/135945758900300202",source:"Artículo fundacional",group:"Vibroacústica y sonido",evidence:"Historia científica"},
  {name:"Tony Wigram",initials:"TW",field:"Musicoterapia e investigación clínica",bio:"Profesor de musicoterapia en Aalborg University y referente internacional en investigación, formación doctoral y práctica clínica de la musicoterapia.",contribution:"Contribuyó a evaluar, enseñar y difundir la terapia vibroacústica, integrándola en un marco clínico y metodológico más amplio.",href:"https://vbn.aau.dk/en/publications/vibroacoustic-therapy-with-adult-patients-with-profound-learning",source:"Aalborg University",group:"Vibroacústica y sonido",evidence:"Investigación clínica"},
  {name:"Marko Punkanen",initials:"MP",field:"Musicoterapia, cuerpo y trauma",bio:"Musicoterapeuta, terapeuta de movimiento, psicoterapeuta e investigador finlandés especializado en procesos corporales y trauma.",contribution:"Integra vibración, música, movimiento y psicoterapia en modelos clínicos que observan la experiencia corporal como vía de regulación.",href:"https://www.vibrac.fi/about-us/",source:"VIBRAC Finland",group:"Vibroacústica y sonido",evidence:"Práctica clínica"},
  {name:"Esa Ala‑Ruona",initials:"EA",field:"Musicoterapia y vibroacústica",bio:"Profesor asociado y director de departamento en la Universidad de Jyväskylä; musicoterapeuta y psicoterapeuta con trayectoria clínica y académica.",contribution:"Estudia evaluación, interacción y procesos clínicos en musicoterapia, incluyendo terapia vibroacústica y modelos multimodales.",href:"https://www.jyu.fi/en/people/esa-ala-ruona",source:"Universidad de Jyväskylä",group:"Vibroacústica y sonido",evidence:"Investigación académica"},
  {name:"Thomas D. Rossing",initials:"TR",field:"Acústica musical",bio:"Físico y profesor reconocido por su trabajo en acústica, instrumentos musicales y modos de vibración.",contribution:"Su investigación permite comprender la física de gongs, placas, campanas y percusión: espectro, resonancia, parciales y distribución modal.",href:"https://archives.stanford.edu/download/m1711.pdf",source:"Stanford Archives",group:"Vibroacústica y sonido",evidence:"Física experimental"},

  {name:"Stephen W. Porges",initials:"SP",field:"Regulación autonómica",bio:"Neurocientífico conductual y creador de la Teoría Polivagal, un marco influyente para relacionar estado autonómico, conducta social y percepción de seguridad.",contribution:"Aporta un lenguaje para estudiar cómo las señales del entorno y la voz se relacionan con regulación autonómica, conexión y defensa.",href:"https://www.polyvagalinstitute.org/about-stephen",source:"Polyvagal Institute",group:"Sistema nervioso y regulación",evidence:"Modelo teórico",featured:true},
  {name:"Bruce S. McEwen",initials:"BM",field:"Estrés, cerebro y alostasis",bio:"Neuroendocrinólogo de Rockefeller University que estudió durante seis décadas la interacción entre experiencia, estrés, cerebro y cuerpo.",contribution:"Desarrolló el concepto de carga alostática para explicar cómo la adaptación sostenida puede acumular desgaste fisiológico.",href:"https://www.rockefeller.edu/news/27135-neuroscientist-bruce-mcewen-studied-impact-stress-brain-died/",source:"Rockefeller University",group:"Sistema nervioso y regulación",evidence:"Ciencia consolidada"},
  {name:"Julian F. Thayer",initials:"JT",field:"HRV y neurovisceralidad",bio:"Psicofisiólogo especializado en variabilidad de la frecuencia cardíaca, emoción, atención, estrés y autorregulación.",contribution:"Cocreador del modelo de integración neurovisceral, que vincula redes prefrontales, flexibilidad autonómica y HRV.",href:"https://psychology.osu.edu/people/thayer.39",source:"Ohio State University",group:"Sistema nervioso y regulación",evidence:"Modelo con evidencia"},
  {name:"Richard D. Lane",initials:"RL",field:"Emoción y cerebro‑cuerpo",bio:"Psiquiatra y neurocientífico de la Universidad de Arizona, pionero en neuroimagen funcional de la emoción y conciencia emocional.",contribution:"Cocreador del modelo de integración neurovisceral y estudioso de cómo la conciencia emocional participa en la regulación cerebro‑cuerpo.",href:"https://medicine.arizona.edu/person/richard-d-lane-md-phd",source:"University of Arizona",group:"Sistema nervioso y regulación",evidence:"Investigación neurocientífica"},
  {name:"Rollin McCraty",initials:"RM",field:"HRV y autorregulación",bio:"Psicofisiólogo y director de investigación del HeartMath Institute, con publicaciones sobre HRV, emoción y técnicas de autorregulación.",contribution:"Desarrolló protocolos y métricas propietarias de coherencia cardíaca que complementan las métricas temporales y frecuenciales de HRV.",href:"https://www.heartmath.org/research/research-library/",source:"HeartMath Institute",group:"Sistema nervioso y regulación",evidence:"Investigación aplicada"},
  {name:"J. Andrew Armour",initials:"JA",field:"Neurocardiología",bio:"Médico e investigador pionero del sistema nervioso cardíaco intrínseco y de los circuitos neuronales que regulan el corazón.",contribution:"Describió la complejidad funcional del sistema nervioso intrínseco del corazón y consolidó la neurocardiología como campo de estudio.",href:"https://academic.oup.com/book/50708",source:"Oxford Academic",group:"Sistema nervioso y regulación",evidence:"Neurofisiología"},
  {name:"Antonio Damasio",initials:"AD",field:"Interocepción, emoción y decisión",bio:"Neurocientífico de USC, director del Brain and Creativity Institute y autor de una obra central sobre emoción, conciencia y cuerpo.",contribution:"La hipótesis del marcador somático explica cómo las señales corporales y emocionales participan en el razonamiento y la toma de decisiones.",href:"https://dornsife.usc.edu/profile/antonio-damasio/",source:"University of Southern California",group:"Sistema nervioso y regulación",evidence:"Neurociencia",featured:true},

  {name:"Robert Schleip",initials:"RS",field:"Fascia y mecanosensación",bio:"Biólogo humano, psicólogo y director del Fascia Research Project, dedicado a la fisiología y arquitectura del tejido fascial.",contribution:"Impulsó el estudio de la fascia como tejido dinámico, inervado y adaptable, relevante para carga, movimiento y percepción corporal.",href:"https://www.fasciaresearch.de/",source:"Fascia Research Project",group:"Fascia, células y mecanobiología",evidence:"Investigación tisular",featured:true},
  {name:"Donald E. Ingber",initials:"DI",field:"Mecanobiología y tensegridad celular",bio:"Médico, bioingeniero y fundador del Wyss Institute de Harvard, referente en diseño biológico, mecanobiología y órganos‑en‑chips.",contribution:"Demostró cómo la arquitectura del citoesqueleto y las fuerzas físicas participan en la mecanotransducción y el comportamiento celular.",href:"https://wyss.harvard.edu/team/core-faculty/donald-ingber/",source:"Wyss Institute · Harvard",group:"Fascia, células y mecanobiología",evidence:"Biología experimental"},
  {name:"Robert O. Becker",initials:"RB",field:"Bioelectricidad y regeneración",bio:"Cirujano ortopédico e investigador estadounidense que estudió potenciales eléctricos en tejido vivo, hueso y procesos regenerativos.",contribution:"Ayudó a establecer la bioelectricidad como variable fisiológica medible y estimuló nuevas preguntas sobre reparación y organización tisular.",href:"https://robertobecker.net/",source:"Archivo biográfico",group:"Fascia, células y mecanobiología",evidence:"Historia de la ciencia"},
  {name:"Andrew E. Pelling",initials:"AP",field:"Mecánica celular",bio:"Biofísico y profesor de la Universidad de Ottawa que estudia propiedades mecánicas de sistemas celulares a escala nano y micrométrica.",contribution:"Coautor de los experimentos que registraron movimientos nanomecánicos de células vivas y abrieron la línea denominada sonocitología.",href:"https://www.uottawa.ca/faculty-science/professors/andrew-pelling",source:"University of Ottawa",group:"Fascia, células y mecanobiología",evidence:"Nanobiología experimental"},
  {name:"James K. Gimzewski",initials:"JG",field:"Nanociencia y sonocitología",bio:"Profesor distinguido de química en UCLA y especialista en microscopía de sonda, nanomecánica y caracterización celular.",contribution:"Con Pelling, convirtió vibraciones nanométricas de células vivas en señales audibles, creando un puente entre medición mecánica y sonificación.",href:"https://www.chemistry.ucla.edu/directory/gimzewski-james-k/",source:"UCLA",group:"Fascia, células y mecanobiología",evidence:"Nanociencia experimental"},

  {name:"Beverly Rubik",initials:"BR",field:"Biofield science",bio:"Biofísica formada en UC Berkeley y fundadora del Institute for Frontier Science, dedicada a líneas de investigación en biocampo y medicina integrativa.",contribution:"Contribuyó a definir y organizar el biocampo como hipótesis de investigación, promoviendo protocolos para fenómenos todavía exploratorios.",href:"https://frontiersciences.org/leadership.html",source:"Institute for Frontier Science",group:"Campos integrativos y experiencia",evidence:"Línea exploratoria"},
  {name:"Shamini Jain",initials:"SJ",field:"Psiconeuroinmunología y salud integrativa",bio:"Psicóloga clínica, investigadora y fundadora de Consciousness and Healing Initiative; profesora adjunta en UC San Diego.",contribution:"Articula redes interdisciplinarias y revisiones sobre prácticas de sanación, experiencia, inmunidad y biofield science.",href:"https://profiles.ucsd.edu/shamini.jain",source:"UC San Diego",group:"Campos integrativos y experiencia",evidence:"Investigación integrativa"},
  {name:"Richard Hammerschlag",initials:"RH",field:"Metodología en salud integrativa",bio:"Investigador vinculado al Helfgott Research Institute y a la evaluación científica de prácticas complementarias e integrativas.",contribution:"Aportó diseño metodológico, revisiones críticas y criterios de medición para estudiar intervenciones complejas con mayor rigor.",href:"https://nunm.edu/research/about/",source:"Helfgott Research Institute",group:"Campos integrativos y experiencia",evidence:"Metodología"},
  {name:"James L. Oschman",initials:"JO",field:"Síntesis biofísica integrativa",bio:"Biofísico y autor que ha reunido literatura sobre matriz extracelular, señales eléctricas y modelos energéticos del organismo.",contribution:"Su obra propone conexiones integrativas útiles para formular hipótesis; cada conexión gana valor cuando se traduce en variables medibles y contrastables.",href:"https://energyresearch.com/",source:"Nature’s Own Research",group:"Campos integrativos y experiencia",evidence:"Síntesis teórica"},
  {name:"Daniel Goleman",initials:"DG",field:"Inteligencia emocional",bio:"Psicólogo, periodista científico y autor que llevó la inteligencia emocional desde la investigación psicológica hacia la educación y el liderazgo.",contribution:"Popularizó habilidades de autoconciencia, autorregulación, empatía y relación; un antecedente cultural para ampliar la inteligencia hacia el cuerpo.",href:"https://www.danielgoleman.info/about/",source:"Sitio oficial",group:"Campos integrativos y experiencia",evidence:"Síntesis y divulgación"},
  {name:"Bessel van der Kolk",initials:"BK",field:"Trauma y experiencia corporal",bio:"Psiquiatra e investigador clínico dedicado a cómo niñas, niños y adultos se adaptan a experiencias traumáticas.",contribution:"Difundió una comprensión corporal del trauma y promovió estudiar cómo movimiento, ritmo, relación y percepción participan en la recuperación.",href:"https://www.besselvanderkolk.com/about/biography",source:"Sitio oficial",group:"Campos integrativos y experiencia",evidence:"Investigación clínica"},
];

const researcherPhotos: Record<string, ResearcherPhoto> = {
  LB:{src:"/images/researchers/lee-bartel.webp",credit:"VIBRAC Finland",href:"https://www.vibrac.fi/about-us/"},
  OS:{src:"/images/researchers/olav-skille.webp",credit:"VIBRAC Finland",href:"https://www.vibrac.fi/about-us/"},
  TW:{src:"/images/researchers/tony-wigram.webp",credit:"Archivo audiovisual profesional",href:"https://www.youtube.com/watch?v=jpPLsULmFGA",position:"50% 72%"},
  MP:{src:"/images/researchers/marko-punkanen.webp",credit:"VIBRAC Finland",href:"https://www.vibrac.fi/about-us/"},
  EA:{src:"/images/researchers/esa-ala-ruona.webp",credit:"VIBRAC Finland",href:"https://www.vibrac.fi/about-us/"},
  TR:{src:"/images/researchers/thomas-rossing.webp",credit:"Acoustical Society of America",href:"https://asaedcom.org/awards/"},
  SP:{src:"/images/researchers/stephen-porges.webp",credit:"Polyvagal Institute",href:"https://www.polyvagalinstitute.org/about-stephen"},
  BM:{src:"/images/researchers/bruce-mcewen.webp",credit:"Rockefeller University",href:"https://www.rockefeller.edu/news/27135-neuroscientist-bruce-mcewen-studied-impact-stress-brain-died/"},
  JT:{src:"/images/researchers/julian-thayer.webp",credit:"University of California, Irvine",href:"https://socialecology.uci.edu/news/ucis-julian-thayer-receives-highest-honor-health-psychology",position:"52% 34%"},
  RL:{src:"/images/researchers/richard-lane.webp",credit:"University of Arizona",href:"https://medicine.arizona.edu/person/richard-d-lane-md-phd"},
  RM:{src:"/images/researchers/rollin-mccraty.webp",credit:"Galileo Commission",href:"https://galileocommission.org/wp-content/uploads/0999/09/Rollin-New-Headshot.jpg",position:"50% 32%"},
  JA:{src:"/images/researchers/j-andrew-armour.webp",credit:"UCLA Neurocardiology · archivo audiovisual",href:"https://www.youtube.com/watch?v=_XBl70WUbAc",position:"12% 55%"},
  AD:{src:"/images/researchers/antonio-damasio.webp",credit:"University of Southern California",href:"https://dornsife.usc.edu/profile/antonio-damasio/"},
  RS:{src:"/images/researchers/robert-schleip.webp",credit:"AtlasPROfilax",href:"https://www.atlasprofilax.ch/en/article/faszienexperte-dr-schleip-begeistert-von-atlasprofilax",position:"50% 34%"},
  DI:{src:"/images/researchers/donald-ingber.webp",credit:"Harvard Medical School",href:"https://ogephd.hms.harvard.edu/people/donald-elliot-ingber"},
  RB:{src:"/images/researchers/robert-becker.webp",credit:"S. Fischer Verlage",href:"https://www.fischerverlage.de/autor/robert-o-becker-1009070"},
  AP:{src:"/images/researchers/andrew-pelling.webp",credit:"University of Ottawa",href:"https://www.uottawa.ca/research-innovation/cell-mechanics-lab"},
  JG:{src:"/images/researchers/james-gimzewski.webp",credit:"UCLA Health",href:"https://www.uclahealth.org/providers/james-gimzewski"},
  BR:{src:"/images/researchers/beverly-rubik.webp",credit:"Institute of Noetic Sciences",href:"https://noetic.org/profile/beverly-rubik/"},
  SJ:{src:"/images/researchers/shamini-jain.webp",credit:"Consciousness and Healing Initiative",href:"https://www.chi.is/shamini-jain/"},
  RH:{src:"/images/researchers/richard-hammerschlag.webp",credit:"Institute of Noetic Sciences",href:"https://noetic.org/profile/richard-hammerschlag/"},
  JO:{src:"/images/researchers/james-oschman.webp",credit:"Science to Sage Magazine",href:"https://sciencetosagemagazine.com/james-oschman-ph-d/"},
  DG:{src:"/images/researchers/daniel-goleman.webp",credit:"Sitio oficial de Daniel Goleman",href:"https://www.danielgoleman.info/about/",position:"48% 30%"},
  BK:{src:"/images/researchers/bessel-van-der-kolk.webp",credit:"Sitio oficial de Bessel van der Kolk",href:"https://www.besselvanderkolk.com/about/biography",position:"50% 34%"},
};

const groups = [...new Set(researchers.map(r=>r.group))];

export default function Home(){
  return <main>
    <header className="topbar"><a className="brand" href="#inicio" aria-label="Bienestar Vibracional, inicio"><Image src="/images/logo-bienestar-vibracional.png" alt="Bienestar Vibracional" width={190} height={76} unoptimized/></a><nav aria-label="Navegación principal"><a className="course-link" href="#recorrido">13 claves</a><a className="course-link" href="#wibindex">WIBindex</a><a className="course-link" href="/wibindex-somatic">Somatic</a><a className="course-link" href="#investigadores">Investigadores <span>↓</span></a><a className="course-link" href="/casos">CASOS</a></nav></header>
    <div id="inicio" className="hero"><Image className="hero-art" src="/images/gong-vibroacustica-cuerpo.png" alt="Ondas de un Gong encontrándose con el cuerpo humano" fill priority unoptimized sizes="100vw"/><div className="hero-content"><p className="overline">Herramienta profesional · medición somática</p><h1>Tu cliente cambió.<br/><em>¿Cómo lo demostramos?</em></h1><p className="hero-lead">WIBIndex Somatic™ permite medir objetivamente la Inteligencia Somática y seguir su evolución antes, durante y después de una intervención.</p><div className="professional-snapshot"><strong>Inteligencia Somática medible.</strong><span>Una herramienta para médicos, psicólogos, kinesiólogos, fisiatras, coaches, terapeutas de sonido, facilitadores sistémicos, consteladores familiares, 5 Ritmos, Alba Emoting, Ecstatic Dance y profesionales del bienestar que necesitan convertir el cambio observado en indicadores comparables.</span></div><div className="hero-actions-main"><a className="wib-somatic-cta" href="/wibindex-somatic">Conocer WIBIndex Somatic™ <span aria-hidden="true">→</span></a></div><div className="hero-rule"><span>OBSERVAR</span><i>→</i><span>MEDIR</span><i>→</i><span>COMPARAR</span><i>→</i><span>SEGUIR EVOLUCIÓN</span></div><p className="caution">No reemplaza el criterio profesional. Lo complementa con indicadores visuales y trazables.</p></div></div>
    <div className="manifesto"><p>La vibroacústica se fundamenta en un fenómeno físico.</p><h2>Una vibración encuentra un cuerpo vivo<br/>y se transforma en percepción.</h2></div>
    <figure className="feature-visual"><Image src="/images/el-sonido-tambien-se-siente.png" alt="El sonido también se siente: oído, piel, contacto, respiración y tono corporal" width={1200} height={675} unoptimized/><figcaption>Visual original del Wellness Intelligence Framework · Vibroacústica aplicada</figcaption></figure>
    <section className="researcher-preview" aria-labelledby="preview-title">
      <div className="preview-copy"><p className="overline">Personas detrás de la evidencia</p><h2 id="preview-title">La ciencia avanza cuando una pregunta encuentra a quien sabe medirla.</h2><p>De la acústica a la neurociencia, de la fascia a la experiencia corporal: conoce a quienes construyeron las ideas, métodos y preguntas que sostienen este recorrido.</p><a className="preview-cta" href="#investigadores">Explorar el mapa de investigadores <span>↓</span></a></div>
      <div className="preview-stack">
        {researchers.filter(r=>r.featured).map((r,i)=>{const photo=researcherPhotos[r.initials];return <a className="preview-card" href={`#investigador-${r.initials.toLowerCase()}`} key={r.name} style={{"--card-index":i} as CSSProperties}><span className="researcher-avatar" title={`Fotografía: ${photo.credit}`}><Image src={photo.src} alt={`Retrato de ${r.name}`} fill sizes="52px" unoptimized style={{objectPosition:photo.position||"50% 50%"}}/></span><div><small>{r.field}</small><strong>{r.name}</strong><p>{r.contribution}</p></div><b>↘</b></a>})}
      </div>
    </section>
    <div id="recorrido" className="chapters"><div className="table-head"><div><span>RECORRIDO</span><h2>13 claves para comprender la ciencia.</h2></div><p>DOCUMENTACIÓN<br/><small>Base para el curso introductorio</small></p></div>
      {chapters.map(c=><article className="chapter" id={`capitulo-${c.n}`} key={c.n}><div className="chapter-main"><span className="chapter-number">{c.n}</span><div><p className="chapter-tag">{c.tag}</p><h3>{c.title}</h3><strong>{c.lead}</strong><p>{c.body}</p>{c.image&&<figure className="chapter-visual"><Image src={c.image} alt={c.imageAlt||c.title} width={1672} height={941} unoptimized sizes="(max-width: 800px) calc(100vw - 80px), 780px"/><figcaption>Visual científico {c.n} · Bienestar Vibracional</figcaption></figure>}{c.note&&<p className="note">{c.note}</p>}</div></div><aside className="chapter-doc"><span>FICHA {c.n}</span><a href={c.href} target={c.href.startsWith("http")?"_blank":undefined} rel="noreferrer">{c.link}<b>↗</b></a><small>Documento asociado</small></aside></article>)}
    </div>
    <section id="investigadores" className="researchers-section">
      <div className="researchers-intro"><p className="overline light">Investigadores</p><h2>Un mapa humano de la ciencia vibroacústica.</h2><div><p>Estas trayectorias conectan física, biología, neurociencia, práctica clínica y exploración integrativa. Cada ficha presenta el campo desde el que investiga, su aporte al marco y una fuente principal para continuar estudiando.</p><p className="evidence-note"><span>Lectura científica</span> El mapa diferencia investigación experimental, modelos teóricos, práctica clínica y líneas exploratorias para que cada idea conserve su contexto.</p></div></div>
      {groups.map((group,groupIndex)=><div className="researcher-group" key={group}><div className="group-title"><span>0{groupIndex+1}</span><h3>{group}</h3><p>{researchers.filter(r=>r.group===group).length} perfiles</p></div><div className="researcher-grid">
        {researchers.filter(r=>r.group===group).map(r=>{const photo=researcherPhotos[r.initials];return <article className="researcher-card" id={`investigador-${r.initials.toLowerCase()}`} key={r.name}><div className="researcher-head"><span className="researcher-avatar" title={`Fotografía: ${photo.credit}`}><Image src={photo.src} alt={`Retrato de ${r.name}`} fill sizes="68px" unoptimized style={{objectPosition:photo.position||"50% 50%"}}/></span><div className="researcher-identity"><p className="researcher-field">{r.field}</p><h4>{r.name}</h4></div></div><div className="researcher-meta"><span className="evidence-pill">{r.evidence}</span><a className="photo-source" href={photo.href} target="_blank" rel="noreferrer" aria-label={`Fuente de la fotografía de ${r.name}`}>Foto · {photo.credit} ↗</a></div><div className="researcher-text"><small>Trayectoria</small><p>{r.bio}</p><small>Aporte al mapa</small><p>{r.contribution}</p></div><a className="researcher-link" href={r.href} target="_blank" rel="noreferrer"><span>{r.source}</span><b>Visitar ↗</b></a></article>})}
      </div></div>)}
    </section>
    <section id="wibindex" className="measurement-visual">
      <div className="measurement-copy"><p className="overline light">WIBindex · medición trazable</p><h2>Del estímulo vivido<br/>al dato comparable.</h2><p>El WIBindex es el desarrollo metodológico de Bienestar Vibracional para implementar lecturas pre/post consistentes. Organiza los datos de cada sesión, conserva las condiciones de medición y expresa la variación observada en una escala comprensible.</p>
        <aside className="gdv-foundation">
          <p className="gdv-kicker">Qué registra la cámara GDV Bio‑Well</p>
          <h3>Una emisión optoelectrónica estimulada, convertida en imagen y datos.</h3>
          <p>Impulsos eléctricos muy breves estimulan la emisión de electrones —y, en menor medida, fotones— en la superficie de la piel. Las partículas generan una descarga en el gas circundante y producen un resplandor que la cámara registra. El software procesa esas imágenes y compara sus parámetros con una base de datos.</p>
          <p>Bio-Well Inc. reúne estudios que describen correlaciones de los parámetros GDV con variabilidad de la frecuencia cardíaca, presión arterial, transpiración cutánea y nivel de estrés. En el WIBindex, esta información se integra como lectura funcional y exploratoria de la respuesta autonómica.</p>
          <div className="gdv-flow" aria-label="Secuencia física de la medición GDV"><span>Impulso breve</span><b>→</b><span>Emisión</span><b>→</b><span>Resplandor</span><b>→</b><span>Imagen</span><b>→</b><span>Parámetros</span></div>
          <a className="gdv-source" href="https://bio-well.es/que-mide-el-metodo-gdv/" target="_blank" rel="noreferrer">Fundamento técnico · Bio-Well Inc. <b>↗</b></a>
        </aside>
        <div className="wib-versions">
          <article className="wib-version"><div><span className="version-number">1.0</span><span className="version-label">Base GDV</span></div><h3>Estrés + Energía</h3><p>Primera implementación para ordenar los parámetros derivados de las imágenes electrofotónicas GDV en una lectura pre/post de Stress Score y energía disponible.</p></article>
          <article className="wib-version"><div><span className="version-number">1.1</span><span className="version-label">Tres pilares</span></div><h3>Homeostasis funcional</h3><p>Integra Estrés fisiológico, Energía funcional y Balance neurovegetativo con ponderaciones explícitas.</p><code className="wib-formula">ES × 0.35 + EN × 0.30 + BN × 0.35</code></article>
          <article className="wib-version"><div><span className="version-number">2.0</span><span className="version-label">GDV + HRV</span></div><h3>Coherencia cardio‑cerebral</h3><p>Amplía la lectura pre/post incorporando HRV y coherencia de HeartMath a los pilares del WIBindex.</p></article>
        </div>
        <div className="metrics"><span>WIBindex · PRE/POST</span><span>GDV · Registro electrofotónico</span><span>HRV · RMSSD / SDNN</span><span>HeartMath · Coherencia</span></div>
      </div>
      <figure className="wibindex-example"><Image src="/images/wibindex-1-1-ejemplo.webp" alt="Ejemplo anonimizado de una comparación pre y post mediante WIBindex 1.1" width={1055} height={1491} unoptimized/><figcaption>Ejemplo de implementación WIBindex 1.1 · lectura pre/post anonimizada · Bienestar Vibracional</figcaption></figure>
    </section>
    <div id="principios" className="framework"><p className="overline">Framework Bienestar Vibracional</p><h2>Wellness Intelligence<br/><em>Data‑Driven</em></h2><div className="equation" aria-label="Fórmula conceptual del Framework BV"><span>Vibroacústica<small>estímulo mecánico</small></span><b>+</b><span>Inteligencia Somática<small>percibir · interpretar · integrar · regular</small></span><b>+</b><span>WIBindex pre/post<small>versiones 1.0 · 1.1 · 2.0</small></span><b>=</b><span className="result">Aprendizaje<small>personalizado y trazable</small></span></div><div className="somatic-framework-cta professional-tool-cta"><span>Nueva categoría profesional</span><h3>¿Y si pudieras medir lo que hasta hoy solo podías observar?</h3><p>Presentamos WIBIndex Somatic™: el primer índice de Inteligencia Somática para acompañar procesos terapéuticos con datos objetivos. Permite cuantificar regulación del sistema nervioso, registrar evolución, mostrar resultados visuales, mejorar adherencia e integrar distintas disciplinas bajo un mismo lenguaje.</p><p><strong>Del "me siento mejor" al "podemos medir cómo evolucionó".</strong></p><a className="wib-somatic-cta" href="/wibindex-somatic">Solicitar demostración profesional <span aria-hidden="true">→</span></a></div><blockquote>“Educamos desde la vibración y el sonido la Inteligencia Somática, comprendiendo su lenguaje interoceptivo y propioceptivo para habitar el lugar más seguro sobre la Tierra: tu propio cuerpo.”</blockquote><p className="signature">Guillermo M. von der Becke (Don Gong) · Bienestar Vibracional</p></div>
    <footer><Image src="/images/logo-bienestar-vibracional.png" alt="Bienestar Vibracional" width={180} height={72} unoptimized/><p>Inteligencia Somática · Vibroacústica aplicada<br/><a className="footer-somatic-link" href="/wibindex-somatic">WIBIndex Somatic™</a></p><p className="legal">Contenido educativo para comprender la percepción corporal y acompañar decisiones informadas de bienestar.</p></footer>
  </main>
}
